---
sources:
    local:
      - all.yml
      - drupal.yml
      - dotfiles.yml

    url:
      #- name: playbook.yml
      #  url: https://db.tt/VcyI9dvr

    git:
       - name: 'osx'
         repo: 'https://github.com/slac-lab/ansible-osx'
         playbooks:
          - homebrew
          - better-touch-tool.yml
          - iterm2.yml
          - sequel-pro.yml
          - vagrant.yml
          - virtualbox.yml
          - sublime3.yml
          - webstorm.yml