---
sources:
  local:
    - all.yml

  url:
    #- name: playbook.yml
    #  url: https://db.tt/VcyI9dvr

  git:
    - name: 'osx'
      repo: 'https://github.com/slac-lab/ansible-osx'
      playbooks:
         
         - better-touch-tool.yml
         - iterm2.yml
         - sequel-pro.yml
         - usb-overdrive.yml
         - vagrant.yml
         - virtualbox.yml
         - chrome-stable.yml
         - sublime3.yml
         - webstorm.yml