# These are packages that are particularly suited to Drupal Development
---
- hosts: workstation

  tasks:
    - name: get my username
      command: logname
      register: local_username
      delegate_to: 127.0.0.1  

    - name: print from playbook
      debug: msg="in playbooks/playbook.yml as user {{ local_username.stdout }} and /Users/{{local_username.stdout}}"
      
    - name: install apps from homebrew
      sudo: true
      sudo_user: "{{ local_username.stdout }}"
      homebrew: name={{item}} state=present update_homebrew=yes
      with_items:
        - php56
        - php56-http
        - php56-crypto
        - php56-gmagick 
        - php56-mcrypt
        - php56-memcache 
        - php56-mongo 
        - php56-varnish 
        - php56-xdebug 
        - php56-xhgui
        - mysql

    #clone dotfiles that are useful
    - name: Clone dotfiles
      git: repo="https://github.com/SLAC-Lab/{{item}}.git" dest="/Users/{{local_username.stdout}}/.dotfiles/.{{item}}" force=no update=no
      with_items:
        - Web-Team-Bash

    - name: Delete dotfiles
      file: path="/Users/{{local_username.stdout}}/.bash_profile" state=absent

    - name: Symlink dotfiles
      file: path="/Users/{{local_username.stdout}}/.{{ item }}" src="/Users/{{local_username.stdout}}/.dotfiles/.Web-Team-Bash/.{{item}}" state=link
      with_items:
        - bash_profile
        - bash_prompt
        - bashrc

   # we use SASS/Compass with suzy.   
    - name: install gems
      gem: name={{item}} state=latest
      with_items:
        - brewbygems
        - bundler
        - compass
        - compass-susy-plugin

    - name: Start services at login
      file: src=/usr/local/opt/{{ item }}/homebrew.mxcl.{{ item }}.plist path=/Library/LaunchAgents/homebrew.mxcl.{{ item }}.plist state=link force=yes
      with_items: 
        - mysql
        

    - name: Setup launch agents for services
      command: launchctl load "/Users/{{local_username.stdout}}"/Library/LaunchAgents/homebrew.mxcl.{{ item }}.plist
      with_items:
         - mysql

    - name: Create src folder
      file: path="/Users/{{local_username.stdout}}"/src state=directory