# These are packages that are particularly suited to Drupal Development
---
- hosts: workstation
  vars:
    home: /Users/{{local_username}}
    src_home: /Users/{{local_username}}/src
  tasks:
    - name: print from playbook
      debug: msg="in playbooks/playbook.yml as user {{ lookup('env','USER') }}"

    - name: install apps from homebrew
      sudo: false
      homebrew: name={{item}} state=present update_homebrew=yes
      with_items:
        - mackup
        - php56
        - php56-http
        - php56-crypto
        - php56-gmagick 
        - php56-mcrypt
        - php56-memcache 
        - php56-mongo 
        - php56-varnish 
        - php56-xdebug 
        - php56-xhgui
        - mysql56

    #clone dotfiles that are useful
    - name: Clone dotfiles
      git: repo=git@github.com:SLAC-Lab/{{ item }}.git dest={{ home }}/.{{ item }} force=no update=no
      with_items:
        - Web-Team-Bash

    - name: Symlink dotfiles
      file: path={{ home }}/.{{ item }} src={{ home }}/.dotfiles/{{ item }} state=link
      with_items:
        - aliases
        - bash_profile
        - bash_prompt
        - bashrc
        - exports
        - extra
        - functions

    - name: Install z.sh
      get_url: url=https://raw.githubusercontent.com/rupa/z/master/z.sh dest=/usr/local/share/zsh/ mode=0755

    - name: Install z.sh
      get_url: url=https://raw.githubusercontent.com/rupa/z/master/z.1 dest=/usr/local/share/man/man1/

   # we use SASS/Compass with suzy.   
    - name: install gems
      gem: name={{item}} state=latest
      with_items:
        - brewbygems
        - bundler
        - compass
        - suzy
    - name: Start services at login
      file: src=/usr/local/opt/{{ item }}/homebrew.mxcl.{{ item }}.plist path=~/Library/LaunchAgents/homebrew.mxcl.{{ item }}.plist state=link force=yes
      with_items: 
        - mysql
        
    - name: Setup launch agents for services
      command: launchctl load {{ home }}/Library/LaunchAgents/homebrew.mxcl.{{ item }}.plist
        with_items:
          - mysql

    - name: Create src folder
      file: path={{ src_home }} state=directory